class Data {
  getListOfCountries() {
    return [
      "Afghanistan",
      "AFRICA",
      "Albania",
      "Algeria",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "ASIA",
      "Australia",
      "Australia/New Zealand",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia (Plurinational State of)",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Caribbean",
      "Central African Republic",
      "Central America",
      "Central Asia",
      "Chad",
      "Channel Islands",
      "Chile",
      "China",
      "China, Hong Kong SAR",
      "China, Macao SAR",
      "Colombia",
      "Comoros",
      "Congo",
      "Costa Rica",
      "Côte d'Ivoire",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czech Republic",
      "Democratic Republic of the Congo",
      "Dem. People's Republic of Korea",
      "Denmark",
      "Djibouti",
      "Dominican Republic",
      "Eastern Africa",
      "Eastern Asia",
      "Eastern Europe",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "EUROPE",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran (Islamic Republic of)",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "LATIN AMERICA AND THE CARIBBEAN",
      "Latvia",
      "Least developed countries",
      "Lebanon",
      "Lesotho",
      "Less developed regions",
      "Less developed regions, excluding China",
      "Less developed regions, excluding least developed countries",
      "Liberia",
      "Libya",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Melanesia",
      "Mexico",
      "Micronesia",
      "Micronesia (Fed. States of)",
      "Middle Africa",
      "Mongolia",
      "Montenegro",
      "More developed regions",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Northern Africa",
      "NORTHERN AMERICA",
      "Northern Europe",
      "Norway",
      "OCEANIA",
      "Oman",
      "Other non-specified areas",
      "Pakistan",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Polynesia",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Republic of Korea",
      "Republic of Moldova",
      "Réunion",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South America",
      "South-Central Asia",
      "South-Eastern Asia",
      "Southern Africa",
      "Southern Asia",
      "Southern Europe",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "State of Palestine",
      "Sub-Saharan Africa",
      "Sudan",
      "Suriname",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Tajikistan",
      "TFYR Macedonia",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United Republic of Tanzania",
      "United States of America",
      "United States Virgin Islands",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela (Bolivarian Republic of)",
      "Viet Nam",
      "Western Africa",
      "Western Asia",
      "Western Europe",
      "Western Sahara",
      "WORLD",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ];
  }

  getListOfYears() {
    return [1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020, 2022];
  }
}

export default new Data()
